#!/usr/bin/env bash
# fw_gen.sh – Compress and embed Realtek firmware into fw_list.cpp
#
# Usage: scripts/fw_gen.sh
#
# This script:
#  1. Reads each .bin firmware file from rtlwm/firmware/
#  2. Compresses it with zlib (via Python)
#  3. Emits a C array for each file
#  4. Writes rtlwm/firmware/fw_list.cpp containing all arrays + the
#     rtlFwList[] table used by include/FwData.h
#
# Adapted from OpenIntelWireless/itlwm scripts/fw_gen.sh (GPLv2)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FW_DIR="$SCRIPT_DIR/../rtlwm/firmware"
OUT="$FW_DIR/fw_list.cpp"
COMPRESS="$SCRIPT_DIR/zlib_compress_fw.py"

echo "// Auto-generated by fw_gen.sh – do not edit manually" > "$OUT"
echo "#include <FwData.h>" >> "$OUT"
echo "" >> "$OUT"

entries=()

for bin in "$FW_DIR"/*.bin; do
    [ -f "$bin" ] || continue
    name="$(basename "$bin")"
    varname="${name//./_}"
    varname="${varname//-/_}"

    echo "Compressing $name…"
    python3 "$COMPRESS" "$bin" "$bin.zlib"

    echo "static const unsigned char ${varname}_data[] = {" >> "$OUT"
    xxd -i < "$bin.zlib" >> "$OUT"
    echo "};" >> "$OUT"
    echo "static const int ${varname}_size = sizeof(${varname}_data);" >> "$OUT"
    echo "" >> "$OUT"

    entries+=("  { RTL_FW(\"$name\", ${varname}_data, ${varname}_size) },")
    rm "$bin.zlib"
done

echo "const struct FwDesc rtlFwList[] = {" >> "$OUT"
for e in "${entries[@]}"; do
    echo "$e" >> "$OUT"
done
echo "};" >> "$OUT"
echo "const int rtlFwNumber = $(( ${#entries[@]} ));" >> "$OUT"

echo "Done – wrote $OUT"
